language: java
jdk:
- oraclejdk8
#services:
#- cassandra
notifications:
  irc:
    channels:
      - "chat.freenode.net#rhq.next"
    on_success: change
env:
  global:
    secure: mDUhAf474mlads7ZEAf2mWecQxZWgdfcjiBn6+yif0hJoWKQs38HU+jm4EE8UMgGvdn7avIYvdrxKJ9MnjWpncaXJ0366ZYbxP+7pybMk/SA80yr3dCg5gSHosJ9UqMvGga1bzgDeqF9UppKt0kqxgSLLwKAFoY+x70Pp0rIwQg=
addons:
  coverity_scan:
    project:
      name: rhq-project/rhq-metrics
      description: Build submitted via Travis CI
    notification_email: hwr@pilhuhn.de
    build_command_prepend: mvn clean
    build_command: mvn -DskipTests=true compile
    branch_pattern: coverity_scan
before_install:
  - bash .travis.install.cassandra.sh
install: 'mvn -s .travis.maven.settings.xml install -DskipTests=true -B'
script: 'mvn -s .travis.maven.settings.xml verify -Dwildfly.logging.console.level=DEBUG -B'
after_failure: 'bash .travis.diagnose.sh'

