language: java
jdk:
- oraclejdk8
notifications:
  irc:
    channels:
    - chat.freenode.net#hawkular
    on_success: change
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
     #   via the "travis encrypt" command using the project repo's public key
  - secure: "L6KFpEFFEPW/bhH3CCYupYFldtJRKJIRy9E14sV5rFDvyrrNw5DgR4cac6hS4XbwOcv+SQv3lhLa0tBkLnJVR5X584py+tQh2zqdj6l5wfGzDSNLz6GXOzqFBx+UjFK7dnMVN7MQ0YIK+RxENQYpLvN9ofGFgqEKjFS8HK4wo9E="
  - secure: Xl2RWUee61vD7Ka/L9M4c9q03w0pn0H5LECsEH6FOTNwLZZdWnHepvF0n8O4YQiG7RdvnK3UHCOGh7G4J5t4XDOwt45IJ3QtjB7FtVdOhMreXHwbMmE0xn2nGGUmhBuYUNN3oIaVzQxWuozcC3g8gQXln4iJVv/f9ecg5R3eRHI=
  - secure: VIYnvHLr/H+2UpeHPe0UKoTK+l+pv6RcKV9tXfLpGEan6th/nmWjo9jR4ZtQNa90FcjOYexRPSLdaU4/SBlpVUHoR59koQQFfdsK+u8hVGpulOpBR6IUDYNQEris93g9NLJA+5PajhGxGnlUqJRP8QAE3RnGK+rq6nGVmlQd4S4=
  # for pushing the swagger adoc documentation to the website repository
  - secure: 6JUY0hUjTXaRcVHFqt1q06enCXdqZ9qYkgLA/uUoKq4tYBVDaaqF4yB88CRzr3rXpytz2aywH2dR1idZH4zoWzv1jQ/tCiYE7GjLRO2qn9wgCMzBRq8G7Ov5iFnsT+aBsf6Syx2rNXwH206cHXP4JY/CRs0ez9tcO4LlYls7XN8=
addons:
  coverity_scan:
    project:
      name: hawkular/hawkular-metrics
      description: Build submitted via Travis CI
    notification_email: hwr@pilhuhn.de
    build_command_prepend: mvn clean
    build_command: mvn -DskipTests=true compile
    branch_pattern: coverity_scan
before_install:
# Increase max number of processes in order to avoid "OutOfMemoryError: unable to create new native thread"
- ulimit -u 4096
- ulimit -a
- sudo apt-get update -qq
- sudo apt-get install -qq collectd collectd-utils
- bash .travis.install.cassandra.sh
install:
- mvn -version -B
script:
- mvn -s .travis.maven.settings.xml verify -Dwildfly.logging.console.level=DEBUG -B | grep -vF "[INFO] Downloading:" | grep -vF "[INFO] Downloaded:"; test ${PIPESTATUS[0]} -eq 0
after_failure: bash .travis.diagnose.sh
after_success:
- PROJECT_VERSION=`mvn org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.version | grep -v '\['`
- if [[ "$PROJECT_VERSION" =~ .*SNAPSHOT ]] && [[ "${TRAVIS_BRANCH}" = "master" ]] && [[ "${TRAVIS_PULL_REQUEST}" = "false" ]];
  then
    mvn -s .travis.maven.settings.xml deploy -DskipTests ;
    ./.travis.swagger.sh ;
    curl --data "build=true" -X POST https://registry.hub.docker.com/u/hawkular/hawkular-metrics/trigger/5e78d947-bbc3-403d-804d-1b9f92d78ed8/ ;
    curl --data "build=true" -X POST https://registry.hub.docker.com/u/hawkular/hawkular-cassandra/trigger/4c78fb4a-acad-4801-83a7-0794347bbe90/ ;
  fi
